[project]
name = "trading-system"
version = "1.0.0"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "openai",
    "requests", 
    "streamlit",
    "plotly",
    "pandas",
    "numpy",
    "python-dotenv",
    "aiofiles"
]